### ISSUE TITLE
add AbortSignal event unsubscription

### ISSUE THREAD

**Issue by getify** [BYOJS/eventer#1]
needs to be held weakly

**Comment by harik-6** [comment]
First of all that is brilliant doc especially with un-subscription example with GC is 🥇. Would like to contribute. Please let me know If I can.

**Comment by harik-6** [comment]
Will you be able to add context on why AbortSignal needed ?

**Comment by getify** [comment]
@harik-6 https://github.com/BYOJS/eventer?tab=readme-ov-file#abortsignal-unsubscription
